name: MergeTestConfig1

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
    branches:
    - master
    - develop
  workflow_dispatch:

jobs:
  trilogpu01-gcc:
    runs-on: [self-hosted, trilogpu01]
    container:
      image: registry-ex.sandia.gov/trilinos-project/trilinos-containers/rhel8/trilinos-env:gcc-8.5.0
      options: --shm-size=16g
    steps:
      - name: env
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          env
      - name: module list
        shell: bash
        run: |
          bash -l -c "module list"
          printenv PATH
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: clone trilinos-containers
        working-directory: /
        run: bash -l -c "git clone https://gitlab-ex.sandia.gov/trilinos-project/trilinos-containers"
      - name: build trilinos
        working-directory: /
        run: bash -l -c "source /trilinos-containers/dockerfiles/trilinos-gcc-8.5.0-openmpi-4.1/files/launch.sh"
  trilogpu02-oneapi:
    runs-on: [self-hosted, trilogpu02]
    container:
      image: registry-ex.sandia.gov/evho/github-actions-trilinos-containers/oneapi-2023.1.0
      options: --shm-size=16g
    steps:
      - name: env
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          env
      - name: module list
        shell: bash
        run: |
          bash -l -c "module list"
          printenv PATH
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: make dirs
        working-directory: /
        run: |
          mkdir -p /home/Trilinos/src/Trilinos
          mkdir -p /home/Trilinos/install
      - name: clone trilinos
        uses: actions/checkout@v3
        with:
          path: /__w/Trilinos/Trilinos/src/Trilinos
      - name: move trilinos
        working-directory: /__w/Trilinos/Trilinos/src/Trilinos
        run: |
          mv -f * /home/Trilinos/src/Trilinos
      - name: configure trilinos
        working-directory: /home/Trilinos/build/
        run: |
          bash -l -c "./configure.sh"
      - name: CMakeCache.txt
        if: always()
        working-directory: /home/Trilinos/build/
        run: |
          bash -l -c "cat CMakeCache.txt"
      - name: build trilinos
        working-directory: /home/Trilinos/build/
        run: bash -l -c "make -j8 && make install -j8"
      - name: ctest
        working-directory: /home/Trilinos/build/
        run: bash -l -c "ctest -j2"
